### PR TITLE
Add my profile

### PR DESCRIPTION
**Pull request by SuperHotDogCat**

### CODE REVIEW

**Comment by SuperHotDogCat** [comment]
LGTM

**Review by tony998244353 — COMMENTED** [review]
Looks almost good, but I have a small favor to ask.

For the consistency with [Alumni page](https://www.eidos.ic.i.u-tokyo.ac.jp/contents/alumni), we'd like to express `Undergraduate Student` for bachelor course students.

However, yeah, I firstly thought that `Bachelor Course Student` might be better because this corresponds to `Master Course Student` and `Doctoral Course Student`, and considered to update Alumni page.
So I also consulted with Taura-sensei, and it turns out that `Undergraduate Student` is a more commonly used expression. Therefore, we've decided to standardize on this term. 

Thus, I would like to request a fix 🙏

**Comment by tony998244353** [comment]
I'll handle the conflict resolution on my side, so there's no need to worry about it. (But if it bothers you, feel free to fix it.

**Comment by SuperHotDogCat** [comment]
Absolutely LGTM

**Review by tony998244353 — APPROVED** [review]
LGTM too!

**Pull request merged**
